In [1]:
import os
import sys
import pandas as pd
import numpy as np
import scipy
from cv_tools.utils import COCOEvalPlus
import os

import plot_utils as pu
from cv_tools import utils
import config as C

%load_ext autoreload
%autoreload 1
%aimport config
%aimport cv_tools.utils
%aimport plot_utils

/Users/s2785075/miniconda3/envs/cv_tools/lib/python3.9/site-packages/tqdm/auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [4]:
N_FOLDS = 3
CCF = True
results_dir = os.path.join(C.RESULTS_DIR, 'ENHANCE_final_revisions')

# Domain-based splitting evaluation

In [7]:
res_dir = 'FINAL_GROUPS' # domain-based results
eval_type = 'Groups' # domain-based evaluation
results_df = []
for model in ['dt2', 'yolo8']:
    for dataset in C.MAIN_DATASETS:
        for augm in [None, 'NMS50'] + C.ALL_PPS + ['resized_MSRCR_15_80_250_fk', 'resized_MSRCR']:
            if augm == 'NMS50' and dataset != 'DeepFish':
                # comparison of NMS threshold 0.7 vs 0.5 was done only for DeepFish
                continue
            train_data = f'{dataset}.CV.{eval_type}{f".{augm}" if augm else ""}'
            fn = os.path.join(results_dir, 'pickles', f'{res_dir}.{model}.{dataset}.{eval_type}.{augm}.pckl')
            if not os.path.exists(fn):
                try:
                    results = utils.read_and_eval_results(
                        train_datas=train_data,
                        models=[model],
                        model_selects=['best'],
                        seeds=C.ALL_SEEDS[dataset],
                        splits=['test'],
                        results_dir=os.path.join(results_dir, res_dir),
                        n_folds=N_FOLDS,
                        concat=CCF,
                        verbose=False,
                    )
                    utils.clean_cached_results(results)
                    utils.pickle_dump(results, fn)
                except:
                    continue
            else:
                results = utils.pickle_load(fn)

            r = results[train_data][model]['best']['test']
            aps = [r[s].precision.mean() for s in r]
            print(f'{model} {train_data} {np.mean(aps):.6f} {np.std(aps):.3f} {[round(ap, 3) for ap in aps]}')
            results_df.append((model, dataset, augm, eval_type, np.mean(aps), np.std(aps), aps))
results_df = pd.DataFrame.from_records(results_df, columns=['model', 'dataset', 'pps', 'eval', 'mAP', 'std', 'mAPs'])
results_df.to_csv(os.path.join(results_dir, f'{res_dir}.csv'), index=None)
results_df

dt2 DeepFish.CV.Groups 0.468151 0.055 [0.419, 0.545, 0.44]
dt2 DeepFish.CV.Groups.NMS50 0.475525 0.046 [0.448, 0.54, 0.438]
dt2 DeepFish.CV.Groups.unsharp_mask 0.469915 0.061 [0.468, 0.545, 0.397]
dt2 DeepFish.CV.Groups.adjust_gamma_down 0.452319 0.030 [0.432, 0.494, 0.431]
dt2 DeepFish.CV.Groups.adjust_gamma_up 0.464464 0.025 [0.474, 0.489, 0.431]
dt2 DeepFish.CV.Groups.adjust_log 0.481267 0.047 [0.48, 0.54, 0.424]
dt2 DeepFish.CV.Groups.adjust_sigmoid 0.413345 0.042 [0.403, 0.469, 0.368]
dt2 DeepFish.CV.Groups.DCP 0.466290 0.040 [0.485, 0.503, 0.411]
dt2 DeepFish.CV.Groups.CAP 0.471537 0.012 [0.488, 0.459, 0.468]
dt2 DeepFish.CV.Groups.FUnIE-GAN 0.461266 0.037 [0.428, 0.513, 0.442]
dt2 DeepFish.CV.Groups.CLAHE 0.499712 0.048 [0.464, 0.568, 0.467]
dt2 DeepFish.CV.Groups.autocontrast 0.487967 0.072 [0.436, 0.59, 0.439]
dt2 DeepFish.CV.Groups.grey_world 0.505223 0.040 [0.521, 0.545, 0.45]
dt2 DeepFish.CV.Groups.ace 0.498423 0.058 [0.448, 0.58, 0.467]
dt2 DeepFish.CV.Groups.ARCR 0.500150 0.036 [0.506, 0.541, 0.454]
dt2 DeepFish.CV.Groups.MLLE 0.516632 0.030 [0.498, 0.559, 0.493]
dt2 DeepFish.CV.Groups.resized_MSRCR_15_80_250_new 0.522834 0.028 [0.483, 0.54, 0.545]
dt2 DeepFish.CV.Groups.resized_MSRCR_15_80_250_fk 0.519724 0.030 [0.484, 0.557, 0.518]
dt2 DeepFish.CV.Groups.resized_MSRCR 0.532814 0.018 [0.514, 0.556, 0.528]
dt2 GLOW_low_visibility_estuaries.CV.Groups 0.526182 0.021 [0.545, 0.496, 0.537]
dt2 GLOW_low_visibility_estuaries.CV.Groups.unsharp_mask 0.504777 0.023 [0.535, 0.5, 0.479]
dt2 GLOW_low_visibility_estuaries.CV.Groups.adjust_gamma_down 0.513179 0.025 [0.544, 0.484, 0.511]
dt2 GLOW_low_visibility_estuaries.CV.Groups.adjust_gamma_up 0.503475 0.033 [0.543, 0.506, 0.462]
dt2 GLOW_low_visibility_estuaries.CV.Groups.adjust_log 0.475955 0.018 [0.5, 0.459, 0.469]
dt2 GLOW_low_visibility_estuaries.CV.Groups.adjust_sigmoid 0.468287 0.025 [0.501, 0.441, 0.463]
dt2 GLOW_low_visibility_estuaries.CV.Groups.DCP 0.498690 0.038 [0.552, 0.471, 0.473]
dt2 GLOW_low_visibility_estuaries.CV.Groups.CAP 0.475638 0.052 [0.519, 0.402, 0.505]
dt2 GLOW_low_visibility_estuaries.CV.Groups.FUnIE-GAN 0.448103 0.005 [0.45, 0.441, 0.454]
dt2 GLOW_low_visibility_estuaries.CV.Groups.CLAHE 0.526650 0.003 [0.527, 0.529, 0.523]
dt2 GLOW_low_visibility_estuaries.CV.Groups.autocontrast 0.568547 0.021 [0.599, 0.551, 0.556]
dt2 GLOW_low_visibility_estuaries.CV.Groups.grey_world 0.559270 0.023 [0.59, 0.553, 0.535]
dt2 GLOW_low_visibility_estuaries.CV.Groups.ace 0.575221 0.012 [0.559, 0.588, 0.579]
dt2 GLOW_low_visibility_estuaries.CV.Groups.ARCR 0.556154 0.010 [0.569, 0.556, 0.544]
dt2 GLOW_low_visibility_estuaries.CV.Groups.MLLE 0.576535 0.021 [0.6, 0.549, 0.58]
dt2 GLOW_low_visibility_estuaries.CV.Groups.resized_MSRCR_15_80_250_new 0.577225 0.023 [0.575, 0.55, 0.607]
dt2 GLOW_low_visibility_estuaries.CV.Groups.resized_MSRCR_15_80_250_fk 0.550552 0.051 [0.485, 0.56, 0.607]
dt2 GLOW_low_visibility_estuaries.CV.Groups.resized_MSRCR 0.578127 0.022 [0.602, 0.549, 0.583]
dt2 Jellytoring.CV.Groups 0.430812 0.023 [0.461, 0.426, 0.406]
dt2 Jellytoring.CV.Groups.unsharp_mask 0.426228 0.014 [0.445, 0.423, 0.411]
dt2 Jellytoring.CV.Groups.adjust_gamma_down 0.432331 0.017 [0.455, 0.413, 0.429]
dt2 Jellytoring.CV.Groups.adjust_gamma_up 0.424819 0.004 [0.419, 0.429, 0.427]
dt2 Jellytoring.CV.Groups.adjust_log 0.430753 0.025 [0.466, 0.416, 0.411]
dt2 Jellytoring.CV.Groups.adjust_sigmoid 0.404827 0.022 [0.436, 0.386, 0.392]
dt2 Jellytoring.CV.Groups.DCP 0.424392 0.021 [0.454, 0.415, 0.405]
dt2 Jellytoring.CV.Groups.CAP 0.390955 0.022 [0.42, 0.368, 0.386]
dt2 Jellytoring.CV.Groups.FUnIE-GAN 0.429415 0.016 [0.453, 0.419, 0.416]
dt2 Jellytoring.CV.Groups.CLAHE 0.419591 0.017 [0.44, 0.398, 0.42]
dt2 Jellytoring.CV.Groups.autocontrast 0.461562 0.019 [0.487, 0.442, 0.455]
dt2 Jellytoring.CV.Groups.grey_world 0.454922 0.024 [0.489, 0.434, 0.442]
dt2 Jellytoring.CV.Groups.ace 0.447316 0.027 [0.485, 0.432, 0.425]
dt2 Jellytoring.CV.Groups.ARCR 0.437665 0.007 [0.441, 0.444, 0.429]
dt2 Jellytoring.CV.Groups.MLLE 0.445650 0.014 [0.455, 0.456, 0.426]
dt2 Jellytoring.CV.Groups.resized_MSRCR_15_80_250_new 0.463026 0.029 [0.504, 0.442, 0.443]
dt2 Jellytoring.CV.Groups.resized_MSRCR_15_80_250_fk 0.451658 0.028 [0.491, 0.43, 0.434]
dt2 Jellytoring.CV.Groups.resized_MSRCR 0.463267 0.025 [0.498, 0.442, 0.449]
yolo8 DeepFish.CV.Groups 0.416163 0.043 [0.375, 0.475, 0.399]
yolo8 DeepFish.CV.Groups.NMS50 0.421935 0.042 [0.38, 0.479, 0.406]
yolo8 DeepFish.CV.Groups.unsharp_mask 0.391837 0.029 [0.351, 0.418, 0.406]
yolo8 DeepFish.CV.Groups.adjust_gamma_down 0.397449 0.077 [0.336, 0.506, 0.351]
yolo8 DeepFish.CV.Groups.adjust_gamma_up 0.451570 0.022 [0.426, 0.448, 0.48]
yolo8 DeepFish.CV.Groups.adjust_log 0.406325 0.045 [0.397, 0.465, 0.357]
yolo8 DeepFish.CV.Groups.adjust_sigmoid 0.403855 0.041 [0.461, 0.385, 0.365]
yolo8 DeepFish.CV.Groups.DCP 0.536528 0.033 [0.533, 0.579, 0.498]
yolo8 DeepFish.CV.Groups.CAP 0.488256 0.032 [0.448, 0.526, 0.491]
yolo8 DeepFish.CV.Groups.FUnIE-GAN 0.390132 0.085 [0.374, 0.502, 0.294]
yolo8 DeepFish.CV.Groups.CLAHE 0.480958 0.076 [0.419, 0.588, 0.436]
yolo8 DeepFish.CV.Groups.autocontrast 0.444916 0.060 [0.361, 0.494, 0.48]
yolo8 DeepFish.CV.Groups.grey_world 0.481482 0.026 [0.482, 0.513, 0.449]
yolo8 DeepFish.CV.Groups.ace 0.458630 0.061 [0.466, 0.528, 0.381]
yolo8 DeepFish.CV.Groups.ARCR 0.483699 0.030 [0.525, 0.468, 0.458]
yolo8 DeepFish.CV.Groups.MLLE 0.539912 0.041 [0.516, 0.598, 0.506]
yolo8 DeepFish.CV.Groups.resized_MSRCR_15_80_250_new 0.550555 0.012 [0.566, 0.55, 0.535]
yolo8 DeepFish.CV.Groups.resized_MSRCR_15_80_250_fk 0.522149 0.021 [0.512, 0.551, 0.503]
yolo8 DeepFish.CV.Groups.resized_MSRCR 0.554843 0.033 [0.595, 0.514, 0.555]
yolo8 GLOW_low_visibility_estuaries.CV.Groups 0.468726 0.018 [0.465, 0.449, 0.493]
yolo8 GLOW_low_visibility_estuaries.CV.Groups.unsharp_mask 0.479753 0.020 [0.451, 0.497, 0.491]
yolo8 GLOW_low_visibility_estuaries.CV.Groups.adjust_gamma_down 0.437104 0.015 [0.418, 0.438, 0.455]
yolo8 GLOW_low_visibility_estuaries.CV.Groups.adjust_gamma_up 0.469152 0.025 [0.441, 0.501, 0.465]
yolo8 GLOW_low_visibility_estuaries.CV.Groups.adjust_log 0.465799 0.025 [0.468, 0.434, 0.495]
yolo8 GLOW_low_visibility_estuaries.CV.Groups.adjust_sigmoid 0.452416 0.014 [0.434, 0.468, 0.455]
yolo8 GLOW_low_visibility_estuaries.CV.Groups.DCP 0.473807 0.028 [0.495, 0.435, 0.491]
yolo8 GLOW_low_visibility_estuaries.CV.Groups.CAP 0.485243 0.029 [0.517, 0.447, 0.492]
yolo8 GLOW_low_visibility_estuaries.CV.Groups.FUnIE-GAN 0.457440 0.008 [0.466, 0.447, 0.46]
yolo8 GLOW_low_visibility_estuaries.CV.Groups.CLAHE 0.484107 0.034 [0.438, 0.495, 0.519]
yolo8 GLOW_low_visibility_estuaries.CV.Groups.autocontrast 0.540780 0.017 [0.564, 0.523, 0.535]
yolo8 GLOW_low_visibility_estuaries.CV.Groups.grey_world 0.527727 0.030 [0.554, 0.544, 0.485]
yolo8 GLOW_low_visibility_estuaries.CV.Groups.ace 0.528462 0.013 [0.546, 0.526, 0.514]
yolo8 GLOW_low_visibility_estuaries.CV.Groups.ARCR 0.539053 0.027 [0.578, 0.523, 0.516]
yolo8 GLOW_low_visibility_estuaries.CV.Groups.MLLE 0.535645 0.035 [0.556, 0.565, 0.486]
yolo8 GLOW_low_visibility_estuaries.CV.Groups.resized_MSRCR_15_80_250_new 0.556715 0.026 [0.557, 0.525, 0.589]
yolo8 GLOW_low_visibility_estuaries.CV.Groups.resized_MSRCR_15_80_250_fk 0.573565 0.015 [0.586, 0.552, 0.583]
yolo8 GLOW_low_visibility_estuaries.CV.Groups.resized_MSRCR 0.560857 0.024 [0.567, 0.529, 0.587]
yolo8 Jellytoring.CV.Groups 0.403464 0.020 [0.431, 0.384, 0.395]
yolo8 Jellytoring.CV.Groups.unsharp_mask 0.415079 0.040 [0.471, 0.392, 0.382]
yolo8 Jellytoring.CV.Groups.adjust_gamma_down 0.423175 0.024 [0.451, 0.425, 0.393]
yolo8 Jellytoring.CV.Groups.adjust_gamma_up 0.426539 0.014 [0.44, 0.433, 0.407]
yolo8 Jellytoring.CV.Groups.adjust_log 0.425788 0.024 [0.459, 0.419, 0.4]
yolo8 Jellytoring.CV.Groups.adjust_sigmoid 0.377968 0.019 [0.399, 0.381, 0.354]
yolo8 Jellytoring.CV.Groups.DCP 0.397035 0.020 [0.425, 0.383, 0.384]
yolo8 Jellytoring.CV.Groups.CAP 0.381035 0.015 [0.403, 0.37, 0.37]
yolo8 Jellytoring.CV.Groups.FUnIE-GAN 0.397498 0.026 [0.435, 0.379, 0.379]
yolo8 Jellytoring.CV.Groups.CLAHE 0.423898 0.015 [0.444, 0.418, 0.409]
yolo8 Jellytoring.CV.Groups.autocontrast 0.455932 0.020 [0.484, 0.442, 0.442]
yolo8 Jellytoring.CV.Groups.grey_world 0.424661 0.038 [0.454, 0.449, 0.371]
yolo8 Jellytoring.CV.Groups.ace 0.433051 0.031 [0.476, 0.413, 0.41]
yolo8 Jellytoring.CV.Groups.ARCR 0.447428 0.011 [0.461, 0.446, 0.435]
yolo8 Jellytoring.CV.Groups.MLLE 0.436538 0.038 [0.49, 0.41, 0.41]
yolo8 Jellytoring.CV.Groups.resized_MSRCR_15_80_250_new 0.456090 0.036 [0.504, 0.419, 0.445]
yolo8 Jellytoring.CV.Groups.resized_MSRCR_15_80_250_fk 0.462523 0.018 [0.486, 0.459, 0.442]
yolo8 Jellytoring.CV.Groups.resized_MSRCR 0.455068 0.038 [0.507, 0.437, 0.421]

,model,dataset,pps,eval,mAP,std,mAPs
0,dt2,DeepFish,None,Groups,0.468151,0.054874,"[0.41930351518172104, 0.5447968724647027, 0.44..."
1,dt2,DeepFish,NMS50,Groups,0.475525,0.045539,"[0.44846496988276124, 0.5396655405530153, 0.43..."
2,dt2,DeepFish,unsharp_mask,Groups,0.469915,0.060674,"[0.4680758227075385, 0.5451282646687295, 0.396..."
3,dt2,DeepFish,adjust_gamma_down,Groups,0.452319,0.029787,"[0.43179192284221707, 0.4944398469998151, 0.43..."
4,dt2,DeepFish,adjust_gamma_up,Groups,0.464464,0.024720,"[0.47389456268877356, 0.4889011532668118, 0.43..."
...,...,...,...,...,...,...,...
105,yolo8,Jellytoring,ARCR,Groups,0.447428,0.010548,"[0.4610701852302508, 0.44583193559763806, 0.43..."
106,yolo8,Jellytoring,MLLE,Groups,0.436538,0.037544,"[0.4896312980548013, 0.41034850972737963, 0.40..."
107,yolo8,Jellytoring,resized_MSRCR_15_80_250_new,Groups,0.456090,0.035755,"[0.5044337307964225, 0.4190796213080974, 0.444..."
108,yolo8,Jellytoring,resized_MSRCR_15_80_250_fk,Groups,0.462523,0.018279,"[0.4863945929914695, 0.4591778691073969, 0.441..."
109,yolo8,Jellytoring,resized_MSRCR,Groups,0.455068,0.037637,"[0.5074464603646632, 0.43708162878504275, 0.42..."

# Do not concatenate folds -- needed for estimating variability of traning folds

In [9]:
res_dir = 'FINAL_GROUPS' # domain-based results
eval_type = 'Groups' # domain-based evaluation
augm = None
for model in ['dt2', 'yolo8']:
    for dataset in C.MAIN_DATASETS:
        train_data = f'{dataset}.CV.{eval_type}{f".{augm}" if augm else ""}'
        fn = os.path.join(results_dir, 'pickles', f'{res_dir}.{model}.{dataset}.{eval_type}.{augm}.concatFalse.pckl')
        if not os.path.exists(fn):
            try:
                results = utils.read_and_eval_results(
                    train_datas=train_data,
                    models=[model],
                    model_selects=['best'],
                    seeds=C.ALL_SEEDS[dataset],
                    splits=['test'],
                    results_dir=os.path.join(results_dir, res_dir),
                    n_folds=N_FOLDS,
                    concat=False,
                    verbose=False,
                )
                utils.clean_cached_results(results)
                utils.pickle_dump(results, fn)
            except:
                continue
        else:
            results = utils.pickle_load(fn)

        r = results[train_data][model]['best']['test']
        aps = [np.mean([r[s][f].precision.mean() for f in range(len(r[s]))]) for s in r]
        print(f'{model} {train_data} {np.mean(aps):.3f} {np.std(aps):.3f} {[round(ap, 3) for ap in aps]}')

dt2 DeepFish.CV.Groups 0.494 0.045 [0.473, 0.556, 0.453]

/Users/s2785075/work/projects/jellies/src/cv_tools/utils.py:546: RuntimeWarning: invalid value encountered in long_scalars
  recall = np.asarray([TPs[k] / (TPs[k] + FNs[k]) for k in range(len(self._paramsEval.catIds))])

dt2 GLOW_low_visibility_estuaries.CV.Groups 0.483 0.039 [0.531, 0.437, 0.483]

/Users/s2785075/work/projects/jellies/src/cv_tools/utils.py:545: RuntimeWarning: invalid value encountered in long_scalars
  precision = np.asarray([TPs[k] / (TPs[k] + FPs[k]) for k in range(len(self._paramsEval.catIds))])

dt2 Jellytoring.CV.Groups 0.418 0.026 [0.454, 0.406, 0.395]
yolo8 DeepFish.CV.Groups 0.440 0.048 [0.41, 0.508, 0.401]
yolo8 GLOW_low_visibility_estuaries.CV.Groups 0.423 0.023 [0.456, 0.409, 0.404]
yolo8 Jellytoring.CV.Groups 0.384 0.027 [0.421, 0.359, 0.372]

# S-UODAC

In [8]:
res_dir = 'FINAL_S-UODAC' # S-UODAC results
eval_type = 'NoValRepro' # evaluate to reproduce S-UODAC evaluation faithfully
results_df = []
dataset = 'S-UODAC'
for model in ['dt2', 'yolo3']:
    for augm in [
        None,
        'resized_MSRCR',
        'resized_MSRCR_15_80_250_new',
    ]:
        tmp_train_data = f'{dataset}.{eval_type}{"E12withGamma" if model == "dt2" else "E100" if model == "yolo3" else ""}{f".{augm}" if augm else ""}'
        fn = os.path.join(results_dir, 'pickles', f'{res_dir}.{model}.{dataset}.{eval_type}.{augm}.pckl')
        train_data = f'{dataset}.{eval_type}{f".{augm}" if augm else ""}'
        if not os.path.exists(fn):
            if model == 'yolo3':
                results = utils.read_and_eval_yolo3(
                    train_datas=tmp_train_data,
                    seeds=C.ALL_SEEDS[dataset],
                    results_dir=os.path.join(results_dir, res_dir),
                    verbose=False,
                    maxDets=300,
                    conf_thr=0.02,
                    fix_zero_ann_ids=True
                )
            else:
                results = utils.read_and_eval_results(
                    train_datas=tmp_train_data,
                    models=[model],
                    model_selects=['last'],
                    seeds=C.ALL_SEEDS[dataset],
                    splits=['test'],
                    results_dir=os.path.join(results_dir, res_dir),
                    n_folds=None,
                    verbose=False,
                    maxDets=300,
                    conf_thr=0.05,
                    fix_zero_ann_ids=True
                )
            utils.clean_cached_results(results)
            results[train_data] = results[tmp_train_data]
            results.pop(tmp_train_data)
            utils.pickle_dump(results, fn)
        else:
            results = utils.pickle_load(fn)

        print(train_data, model)
        r = results[train_data][model]['last']['test']
        aps = [r[s].precision.mean() for s in r]
        species_aps = np.asarray([r[s].precision.mean(axis=0) for s in r]).mean(axis=0)
        print(f'{model} {train_data} {np.mean(aps):.3f} {np.std(aps):.3f} {[round(ap, 3) for ap in aps]}')
        results_df.append([model, dataset, augm, eval_type, np.mean(aps), np.std(aps), aps] + species_aps.tolist())
results_df = pd.DataFrame.from_records(results_df, columns=['model', 'dataset', 'pps', 'eval', 'mAP', 'std', 'mAPs'] + [f's{i}_AP' for i in range(len(species_aps))])
results_df.to_csv(os.path.join(results_dir, f'{res_dir}.csv'), index=None)
(results_df.set_index(['model', 'dataset', 'pps', 'eval'])[['s0_AP', 's1_AP', 's2_AP', 's3_AP', 'mAP']] * 100).round(2)

S-UODAC.NoValRepro dt2
dt2 S-UODAC.NoValRepro 0.537 0.015 [0.516, 0.551, 0.544]
S-UODAC.NoValRepro.resized_MSRCR dt2
dt2 S-UODAC.NoValRepro.resized_MSRCR 0.645 0.013 [0.628, 0.66, 0.647]
S-UODAC.NoValRepro.resized_MSRCR_15_80_250_new dt2
dt2 S-UODAC.NoValRepro.resized_MSRCR_15_80_250_new 0.631 0.011 [0.617, 0.643, 0.632]
S-UODAC.NoValRepro yolo3
yolo3 S-UODAC.NoValRepro 0.382 0.042 [0.41, 0.413, 0.322]
S-UODAC.NoValRepro.resized_MSRCR yolo3
yolo3 S-UODAC.NoValRepro.resized_MSRCR 0.617 0.004 [0.616, 0.623, 0.613]
S-UODAC.NoValRepro.resized_MSRCR_15_80_250_new yolo3
yolo3 S-UODAC.NoValRepro.resized_MSRCR_15_80_250_new 0.613 0.004 [0.609, 0.618, 0.612]

                                                      s0_AP  s1_AP  s2_AP  \
model dataset pps                         eval
dt2   S-UODAC NaN                         NoValRepro  76.57  41.42  50.31
              resized_MSRCR               NoValRepro  80.35  63.40  56.22
              resized_MSRCR_15_80_250_new NoValRepro  80.94  62.80  56.23
yolo3 S-UODAC NaN                         NoValRepro  68.67  31.10  29.33
              resized_MSRCR               NoValRepro  78.00  58.08  54.33
              resized_MSRCR_15_80_250_new NoValRepro  78.10  61.09  53.46

                                                      s3_AP    mAP
model dataset pps                         eval
dt2   S-UODAC NaN                         NoValRepro  46.46  53.69
              resized_MSRCR               NoValRepro  58.00  64.49
              resized_MSRCR_15_80_250_new NoValRepro  52.33  63.07
yolo3 S-UODAC NaN                         NoValRepro  23.67  38.19
              resized_MSRCR               NoValRepro  56.47  61.72
              resized_MSRCR_15_80_250_new NoValRepro  52.53  61.29

# Random-splitting evaluation (ignore domains)

In [6]:
res_dir = 'FINAL_NO_GROUPS' # random-splitting results
eval_type = 'NoGroups' # random-splittin evaluation
results_df = []
for model in ['dt2', 'yolo8']:
    for dataset in C.MAIN_DATASETS:
        for augm in [None] + C.ALL_PPS:
            train_data = f'{dataset}.CV.{eval_type}{f".{augm}" if augm else ""}'
            fn = os.path.join(results_dir, 'pickles', f'{res_dir}.{model}.{dataset}.{eval_type}.{augm}.pckl')
            if not os.path.exists(fn):
                try:
                    results = utils.read_and_eval_results(
                        train_datas=train_data,
                        models=[model],
                        model_selects=['best'],
                        seeds=C.ALL_SEEDS[dataset],
                        splits=['test'],
                        results_dir=os.path.join(results_dir, res_dir),
                        n_folds=N_FOLDS,
                        concat=CCF,
                        verbose=False,
                    )
                    utils.clean_cached_results(results)
                    utils.pickle_dump(results, fn)
                except:
                    continue
            else:
                results = utils.pickle_load(fn)

            r = results[train_data][model]['best']['test']
            aps = [r[s].precision.mean() for s in r]
            print(f'{model} {train_data} {np.mean(aps):.3f} {np.std(aps):.3f} {[round(ap, 3) for ap in aps]}')
            results_df.append((model, dataset, augm, eval_type, np.mean(aps), np.std(aps), aps))
results_df = pd.DataFrame.from_records(results_df, columns=['model', 'dataset', 'pps', 'eval', 'mAP', 'std', 'mAPs'])
results_df.to_csv(os.path.join(results_dir, f'{res_dir}.csv'), index=None)
results_df

dt2 DeepFish.CV.NoGroups 0.963 0.002 [0.965, 0.96, 0.963]
dt2 DeepFish.CV.NoGroups.unsharp_mask 0.961 0.001 [0.962, 0.962, 0.959]
dt2 DeepFish.CV.NoGroups.adjust_gamma_down 0.961 0.001 [0.959, 0.962, 0.96]
dt2 DeepFish.CV.NoGroups.adjust_gamma_up 0.963 0.002 [0.963, 0.961, 0.965]
dt2 DeepFish.CV.NoGroups.adjust_log 0.961 0.001 [0.959, 0.961, 0.963]
dt2 DeepFish.CV.NoGroups.adjust_sigmoid 0.960 0.001 [0.959, 0.961, 0.96]
dt2 DeepFish.CV.NoGroups.DCP 0.961 0.002 [0.961, 0.959, 0.963]
dt2 DeepFish.CV.NoGroups.CAP 0.959 0.001 [0.96, 0.957, 0.96]
dt2 DeepFish.CV.NoGroups.FUnIE-GAN 0.956 0.001 [0.957, 0.955, 0.957]
dt2 DeepFish.CV.NoGroups.CLAHE 0.961 0.001 [0.96, 0.961, 0.961]
dt2 DeepFish.CV.NoGroups.autocontrast 0.961 0.001 [0.961, 0.962, 0.961]
dt2 DeepFish.CV.NoGroups.grey_world 0.962 0.001 [0.963, 0.961, 0.962]
dt2 DeepFish.CV.NoGroups.ace 0.962 0.001 [0.961, 0.962, 0.962]
dt2 DeepFish.CV.NoGroups.ARCR 0.961 0.001 [0.961, 0.96, 0.963]
dt2 DeepFish.CV.NoGroups.MLLE 0.962 0.002 [0.964, 0.963, 0.959]
dt2 DeepFish.CV.NoGroups.resized_MSRCR_15_80_250_new 0.960 0.001 [0.96, 0.959, 0.961]
dt2 GLOW_low_visibility_estuaries.CV.NoGroups 0.862 0.004 [0.866, 0.862, 0.858]
dt2 GLOW_low_visibility_estuaries.CV.NoGroups.unsharp_mask 0.859 0.005 [0.864, 0.853, 0.861]
dt2 GLOW_low_visibility_estuaries.CV.NoGroups.adjust_gamma_down 0.855 0.005 [0.855, 0.862, 0.849]
dt2 GLOW_low_visibility_estuaries.CV.NoGroups.adjust_gamma_up 0.860 0.002 [0.86, 0.857, 0.862]
dt2 GLOW_low_visibility_estuaries.CV.NoGroups.adjust_log 0.859 0.002 [0.857, 0.858, 0.862]
dt2 GLOW_low_visibility_estuaries.CV.NoGroups.adjust_sigmoid 0.859 0.001 [0.86, 0.86, 0.858]
dt2 GLOW_low_visibility_estuaries.CV.NoGroups.DCP 0.852 0.003 [0.852, 0.855, 0.849]
dt2 GLOW_low_visibility_estuaries.CV.NoGroups.CAP 0.853 0.001 [0.853, 0.851, 0.855]
dt2 GLOW_low_visibility_estuaries.CV.NoGroups.FUnIE-GAN 0.849 0.007 [0.84, 0.852, 0.855]
dt2 GLOW_low_visibility_estuaries.CV.NoGroups.CLAHE 0.853 0.002 [0.85, 0.855, 0.854]
dt2 GLOW_low_visibility_estuaries.CV.NoGroups.autocontrast 0.862 0.003 [0.861, 0.859, 0.866]
dt2 GLOW_low_visibility_estuaries.CV.NoGroups.grey_world 0.860 0.003 [0.862, 0.856, 0.861]
dt2 GLOW_low_visibility_estuaries.CV.NoGroups.ace 0.858 0.001 [0.856, 0.858, 0.86]
dt2 GLOW_low_visibility_estuaries.CV.NoGroups.ARCR 0.863 0.002 [0.86, 0.864, 0.865]
dt2 GLOW_low_visibility_estuaries.CV.NoGroups.MLLE 0.862 0.003 [0.859, 0.867, 0.861]
dt2 GLOW_low_visibility_estuaries.CV.NoGroups.resized_MSRCR_15_80_250_new 0.858 0.001 [0.858, 0.859, 0.856]
dt2 Jellytoring.CV.NoGroups 0.903 0.004 [0.908, 0.901, 0.899]
dt2 Jellytoring.CV.NoGroups.unsharp_mask 0.900 0.004 [0.904, 0.896, 0.902]
dt2 Jellytoring.CV.NoGroups.adjust_gamma_down 0.905 0.003 [0.906, 0.907, 0.901]
dt2 Jellytoring.CV.NoGroups.adjust_gamma_up 0.904 0.001 [0.904, 0.904, 0.905]
dt2 Jellytoring.CV.NoGroups.adjust_log 0.903 0.003 [0.903, 0.907, 0.899]
dt2 Jellytoring.CV.NoGroups.adjust_sigmoid 0.898 0.004 [0.903, 0.893, 0.896]
dt2 Jellytoring.CV.NoGroups.DCP 0.901 0.003 [0.897, 0.904, 0.903]
dt2 Jellytoring.CV.NoGroups.CAP 0.897 0.001 [0.898, 0.898, 0.897]
dt2 Jellytoring.CV.NoGroups.FUnIE-GAN 0.898 0.001 [0.898, 0.899, 0.896]
dt2 Jellytoring.CV.NoGroups.CLAHE 0.903 0.001 [0.903, 0.902, 0.904]
dt2 Jellytoring.CV.NoGroups.autocontrast 0.904 0.004 [0.898, 0.908, 0.906]
dt2 Jellytoring.CV.NoGroups.grey_world 0.908 0.003 [0.908, 0.911, 0.904]
dt2 Jellytoring.CV.NoGroups.ace 0.906 0.008 [0.916, 0.897, 0.905]
dt2 Jellytoring.CV.NoGroups.ARCR 0.900 0.003 [0.903, 0.9, 0.895]
dt2 Jellytoring.CV.NoGroups.MLLE 0.900 0.002 [0.897, 0.901, 0.901]
dt2 Jellytoring.CV.NoGroups.resized_MSRCR_15_80_250_new 0.897 0.002 [0.9, 0.897, 0.895]
yolo8 DeepFish.CV.NoGroups 0.964 0.000 [0.964, 0.964, 0.965]
yolo8 DeepFish.CV.NoGroups.unsharp_mask 0.961 0.001 [0.96, 0.96, 0.962]
yolo8 DeepFish.CV.NoGroups.adjust_gamma_down 0.963 0.000 [0.963, 0.963, 0.964]
yolo8 DeepFish.CV.NoGroups.adjust_gamma_up 0.964 0.001 [0.964, 0.964, 0.965]
yolo8 DeepFish.CV.NoGroups.adjust_log 0.963 0.001 [0.963, 0.963, 0.964]
yolo8 DeepFish.CV.NoGroups.adjust_sigmoid 0.962 0.001 [0.96, 0.963, 0.962]
yolo8 DeepFish.CV.NoGroups.DCP 0.962 0.000 [0.962, 0.963, 0.962]
yolo8 DeepFish.CV.NoGroups.CAP 0.959 0.001 [0.958, 0.958, 0.96]
yolo8 DeepFish.CV.NoGroups.FUnIE-GAN 0.961 0.000 [0.961, 0.96, 0.961]
yolo8 DeepFish.CV.NoGroups.CLAHE 0.963 0.000 [0.963, 0.962, 0.963]
yolo8 DeepFish.CV.NoGroups.autocontrast 0.964 0.001 [0.963, 0.963, 0.964]
yolo8 DeepFish.CV.NoGroups.grey_world 0.963 0.000 [0.964, 0.963, 0.963]
yolo8 DeepFish.CV.NoGroups.ace 0.963 0.000 [0.963, 0.963, 0.964]
yolo8 DeepFish.CV.NoGroups.ARCR 0.964 0.001 [0.964, 0.964, 0.963]
yolo8 DeepFish.CV.NoGroups.MLLE 0.961 0.000 [0.961, 0.961, 0.962]
yolo8 DeepFish.CV.NoGroups.resized_MSRCR_15_80_250_new 0.962 0.001 [0.962, 0.961, 0.964]
yolo8 GLOW_low_visibility_estuaries.CV.NoGroups 0.873 0.000 [0.873, 0.874, 0.873]
yolo8 GLOW_low_visibility_estuaries.CV.NoGroups.unsharp_mask 0.873 0.004 [0.873, 0.867, 0.878]
yolo8 GLOW_low_visibility_estuaries.CV.NoGroups.adjust_gamma_down 0.875 0.002 [0.872, 0.877, 0.877]
yolo8 GLOW_low_visibility_estuaries.CV.NoGroups.adjust_gamma_up 0.874 0.002 [0.872, 0.873, 0.876]
yolo8 GLOW_low_visibility_estuaries.CV.NoGroups.adjust_log 0.872 0.003 [0.875, 0.872, 0.868]
yolo8 GLOW_low_visibility_estuaries.CV.NoGroups.adjust_sigmoid 0.874 0.002 [0.871, 0.873, 0.877]
yolo8 GLOW_low_visibility_estuaries.CV.NoGroups.DCP 0.866 0.003 [0.867, 0.863, 0.869]
yolo8 GLOW_low_visibility_estuaries.CV.NoGroups.CAP 0.870 0.003 [0.866, 0.87, 0.874]
yolo8 GLOW_low_visibility_estuaries.CV.NoGroups.FUnIE-GAN 0.867 0.002 [0.866, 0.864, 0.869]
yolo8 GLOW_low_visibility_estuaries.CV.NoGroups.CLAHE 0.874 0.002 [0.872, 0.874, 0.877]
yolo8 GLOW_low_visibility_estuaries.CV.NoGroups.autocontrast 0.875 0.001 [0.873, 0.875, 0.876]
yolo8 GLOW_low_visibility_estuaries.CV.NoGroups.grey_world 0.876 0.002 [0.876, 0.873, 0.878]
yolo8 GLOW_low_visibility_estuaries.CV.NoGroups.ace 0.877 0.002 [0.876, 0.874, 0.879]
yolo8 GLOW_low_visibility_estuaries.CV.NoGroups.ARCR 0.875 0.001 [0.873, 0.875, 0.876]
yolo8 GLOW_low_visibility_estuaries.CV.NoGroups.MLLE 0.875 0.003 [0.871, 0.874, 0.879]
yolo8 GLOW_low_visibility_estuaries.CV.NoGroups.resized_MSRCR_15_80_250_new 0.876 0.003 [0.872, 0.878, 0.878]
yolo8 Jellytoring.CV.NoGroups 0.914 0.002 [0.916, 0.912, 0.914]
yolo8 Jellytoring.CV.NoGroups.unsharp_mask 0.908 0.001 [0.906, 0.91, 0.908]
yolo8 Jellytoring.CV.NoGroups.adjust_gamma_down 0.912 0.003 [0.916, 0.907, 0.912]
yolo8 Jellytoring.CV.NoGroups.adjust_gamma_up 0.912 0.002 [0.913, 0.91, 0.913]
yolo8 Jellytoring.CV.NoGroups.adjust_log 0.913 0.002 [0.916, 0.913, 0.911]
yolo8 Jellytoring.CV.NoGroups.adjust_sigmoid 0.905 0.004 [0.9, 0.91, 0.905]
yolo8 Jellytoring.CV.NoGroups.DCP 0.910 0.004 [0.915, 0.911, 0.905]
yolo8 Jellytoring.CV.NoGroups.CAP 0.902 0.002 [0.901, 0.9, 0.904]
yolo8 Jellytoring.CV.NoGroups.FUnIE-GAN 0.909 0.002 [0.907, 0.91, 0.911]
yolo8 Jellytoring.CV.NoGroups.CLAHE 0.912 0.001 [0.913, 0.914, 0.911]
yolo8 Jellytoring.CV.NoGroups.autocontrast 0.911 0.005 [0.915, 0.913, 0.905]
yolo8 Jellytoring.CV.NoGroups.grey_world 0.916 0.003 [0.92, 0.915, 0.913]
yolo8 Jellytoring.CV.NoGroups.ace 0.914 0.002 [0.914, 0.917, 0.911]
yolo8 Jellytoring.CV.NoGroups.ARCR 0.912 0.000 [0.913, 0.912, 0.912]
yolo8 Jellytoring.CV.NoGroups.MLLE 0.909 0.001 [0.907, 0.911, 0.909]
yolo8 Jellytoring.CV.NoGroups.resized_MSRCR_15_80_250_new 0.908 0.001 [0.909, 0.907, 0.907]

,model,dataset,pps,eval,mAP,std,mAPs
0,dt2,DeepFish,None,NoGroups,0.962876,0.002009,"[0.9653215037420165, 0.9603998665738995, 0.962..."
1,dt2,DeepFish,unsharp_mask,NoGroups,0.961071,0.001353,"[0.961863285694112, 0.9621842288086494, 0.9591..."
2,dt2,DeepFish,adjust_gamma_down,NoGroups,0.960511,0.000977,"[0.9593386865696515, 0.9617305819731189, 0.960..."
3,dt2,DeepFish,adjust_gamma_up,NoGroups,0.962980,0.001518,"[0.9629220187835795, 0.9611513831646608, 0.964..."
4,dt2,DeepFish,adjust_log,NoGroups,0.960937,0.001419,"[0.9592326657160306, 0.9608706187879862, 0.962..."
...,...,...,...,...,...,...,...
91,yolo8,Jellytoring,grey_world,NoGroups,0.915827,0.002817,"[0.919648629015166, 0.9148895229047502, 0.9129..."
92,yolo8,Jellytoring,ace,NoGroups,0.913742,0.002455,"[0.9135652545343936, 0.9168331088414957, 0.910..."
93,yolo8,Jellytoring,ARCR,NoGroups,0.912263,0.000378,"[0.9126948209220188, 0.9123207127338447, 0.911..."
94,yolo8,Jellytoring,MLLE,NoGroups,0.909043,0.001452,"[0.9074451707414273, 0.9109597790260754, 0.908..."
95,yolo8,Jellytoring,resized_MSRCR_15_80_250_new,NoGroups,0.907775,0.000946,"[0.9091013255733329, 0.9069599211494098, 0.907..."

# MLLE combined with MSRCR

In [9]:
res_dir = 'MLLE_MSRCR_combi'
eval_type = 'Groups' # domain-based evaluation
dataset = 'DeepFish'
results_df = []
for model in ['yolo8', 'dt2']:
    for augm in [
        'MLLE_resized_MSRCR',
        'resized_MSRCR_MLLE'
    ]:
        train_data = f'{dataset}.CV.{eval_type}{f".{augm}" if augm else ""}'
        fn = os.path.join(results_dir, 'pickles', f'{res_dir}.{model}.{dataset}.{eval_type}.{augm}.pckl')
        if not os.path.exists(fn):
            results = utils.read_and_eval_results(
                train_datas=train_data,
                models=[model],
                model_selects=['best'],
                seeds=C.ALL_SEEDS[dataset],
                splits=['test'],
                results_dir=os.path.join(results_dir, res_dir),
                n_folds=N_FOLDS,
                concat=CCF,
                verbose=False,
            )
            utils.clean_cached_results(results)
            utils.pickle_dump(results, fn)
        else:
            results = utils.pickle_load(fn)

        r = results[train_data][model]['best']['test']
        aps = [r[s].precision.mean() for s in r]
        print(f'{model} {train_data} {np.mean(aps):.3f} {np.std(aps):.3f} {[round(ap, 3) for ap in aps]}')
        results_df.append((model, dataset, augm, eval_type, np.mean(aps), np.std(aps), aps))
results_df = pd.DataFrame.from_records(results_df, columns=['model', 'dataset', 'pps', 'eval', 'mAP', 'std', 'mAPs'])
results_df.to_csv(os.path.join(results_dir, f'{res_dir}.csv'), index=None)
results_df

yolo8 DeepFish.CV.Groups.MLLE_resized_MSRCR 0.486 0.026 [0.464, 0.523, 0.471]
yolo8 DeepFish.CV.Groups.resized_MSRCR_MLLE 0.537 0.062 [0.573, 0.588, 0.45]
dt2 DeepFish.CV.Groups.MLLE_resized_MSRCR 0.487 0.042 [0.445, 0.545, 0.472]
dt2 DeepFish.CV.Groups.resized_MSRCR_MLLE 0.529 0.022 [0.559, 0.519, 0.509]

,model,dataset,pps,eval,mAP,std,mAPs
0,yolo8,DeepFish,MLLE_resized_MSRCR,Groups,0.485876,0.026191,"[0.46421049413715937, 0.5227259785165099, 0.47..."
1,yolo8,DeepFish,resized_MSRCR_MLLE,Groups,0.537132,0.061568,"[0.5730054276468635, 0.5879019452692945, 0.450..."
2,dt2,DeepFish,MLLE_resized_MSRCR,Groups,0.487162,0.042317,"[0.44463703694020584, 0.5448917615573152, 0.47..."
3,dt2,DeepFish,resized_MSRCR_MLLE,Groups,0.528898,0.021822,"[0.559222268058264, 0.5186969427629908, 0.5087..."

# Training data subsampling

In [10]:
res_dir = 'SUBSAMPLE'
eval_type = 'Groups' # domain-based evaluation
results_df = []
dataset = 'DeepFish'
for model in ['yolo8', 'dt2']:
    for augm in [
        'ssT400',
        'ssT400.ssG50',
        'ssT400.ssG25',
        'ssT1000',
        'ssT1000.ssG50',
    ]:
        for replicate in ['x1', 'x2', 'x3']:
            train_data = f'{dataset}.CV.{eval_type}{f".{augm}.{replicate}" if augm else ""}'
            fn = os.path.join(results_dir, 'pickles', f'{res_dir}.{model}.{dataset}.{eval_type}.{augm}.{replicate}.pckl')
            if not os.path.exists(fn):
                results = utils.read_and_eval_results(
                    train_datas=train_data,
                    models=[model],
                    model_selects=['best'],
                    seeds=C.ALL_SEEDS[dataset],
                    splits=['test'],
                    results_dir=os.path.join(results_dir, res_dir),
                    n_folds=N_FOLDS,
                    concat=CCF,
                    verbose=False,
                )
                utils.clean_cached_results(results)
                utils.pickle_dump(results, fn)
            else:
                results = utils.pickle_load(fn)

            r = results[train_data][model]['best']['test']
            aps = [r[s].precision.mean() for s in r]
            print(f'{model} {train_data} {np.mean(aps):.3f} {np.std(aps):.3f} {[round(ap, 3) for ap in aps]}')
            results_df.append((model, dataset, augm, eval_type, np.mean(aps), np.std(aps), aps))
results_df = pd.DataFrame.from_records(results_df, columns=['model', 'dataset', 'pps', 'eval', 'mAP', 'std', 'mAPs'])
results_df.to_csv(os.path.join(results_dir, f'{res_dir}.csv'), index=None)
results_df

yolo8 DeepFish.CV.Groups.ssT400.x1 0.414 0.041 [0.357, 0.455, 0.428]
yolo8 DeepFish.CV.Groups.ssT400.x2 0.392 0.013 [0.396, 0.375, 0.406]
yolo8 DeepFish.CV.Groups.ssT400.x3 0.402 0.040 [0.391, 0.455, 0.36]
yolo8 DeepFish.CV.Groups.ssT400.ssG50.x1 0.328 0.056 [0.321, 0.4, 0.263]
yolo8 DeepFish.CV.Groups.ssT400.ssG50.x2 0.328 0.056 [0.321, 0.4, 0.263]
yolo8 DeepFish.CV.Groups.ssT400.ssG50.x3 0.328 0.056 [0.321, 0.4, 0.263]
yolo8 DeepFish.CV.Groups.ssT400.ssG25.x1 0.247 0.079 [0.242, 0.347, 0.154]
yolo8 DeepFish.CV.Groups.ssT400.ssG25.x2 0.261 0.124 [0.302, 0.388, 0.093]
yolo8 DeepFish.CV.Groups.ssT400.ssG25.x3 0.283 0.018 [0.302, 0.26, 0.287]
yolo8 DeepFish.CV.Groups.ssT1000.x1 0.419 0.053 [0.357, 0.487, 0.414]
yolo8 DeepFish.CV.Groups.ssT1000.x2 0.432 0.035 [0.385, 0.442, 0.469]
yolo8 DeepFish.CV.Groups.ssT1000.x3 0.435 0.068 [0.429, 0.521, 0.355]
yolo8 DeepFish.CV.Groups.ssT1000.ssG50.x1 0.386 0.031 [0.343, 0.399, 0.416]
yolo8 DeepFish.CV.Groups.ssT1000.ssG50.x2 0.390 0.053 [0.35, 0.465, 0.356]
yolo8 DeepFish.CV.Groups.ssT1000.ssG50.x3 0.392 0.030 [0.428, 0.392, 0.356]
dt2 DeepFish.CV.Groups.ssT400.x1 0.471 0.011 [0.462, 0.487, 0.463]
dt2 DeepFish.CV.Groups.ssT400.x2 0.450 0.061 [0.502, 0.485, 0.364]
dt2 DeepFish.CV.Groups.ssT400.x3 0.452 0.035 [0.419, 0.436, 0.501]
dt2 DeepFish.CV.Groups.ssT400.ssG50.x1 0.411 0.054 [0.425, 0.468, 0.339]
dt2 DeepFish.CV.Groups.ssT400.ssG50.x2 0.437 0.069 [0.426, 0.527, 0.358]
dt2 DeepFish.CV.Groups.ssT400.ssG50.x3 0.395 0.054 [0.379, 0.468, 0.338]
dt2 DeepFish.CV.Groups.ssT400.ssG25.x1 0.381 0.047 [0.364, 0.446, 0.333]
dt2 DeepFish.CV.Groups.ssT400.ssG25.x2 0.363 0.092 [0.345, 0.483, 0.26]
dt2 DeepFish.CV.Groups.ssT400.ssG25.x3 0.343 0.051 [0.378, 0.272, 0.38]
dt2 DeepFish.CV.Groups.ssT1000.x1 0.480 0.032 [0.484, 0.517, 0.438]
dt2 DeepFish.CV.Groups.ssT1000.x2 0.499 0.043 [0.518, 0.541, 0.439]
dt2 DeepFish.CV.Groups.ssT1000.x3 0.474 0.055 [0.468, 0.545, 0.41]
dt2 DeepFish.CV.Groups.ssT1000.ssG50.x1 0.378 0.084 [0.33, 0.496, 0.307]
dt2 DeepFish.CV.Groups.ssT1000.ssG50.x2 0.431 0.081 [0.342, 0.537, 0.413]
dt2 DeepFish.CV.Groups.ssT1000.ssG50.x3 0.469 0.003 [0.473, 0.468, 0.467]

,model,dataset,pps,eval,mAP,std,mAPs
0,yolo8,DeepFish,ssT400,Groups,0.413543,0.041272,"[0.35732015066263945, 0.45523214742739676, 0.4..."
1,yolo8,DeepFish,ssT400,Groups,0.391975,0.012835,"[0.39566839465810344, 0.374737860823817, 0.405..."
2,yolo8,DeepFish,ssT400,Groups,0.402255,0.039612,"[0.3910764335248845, 0.4553836006112906, 0.360..."
3,yolo8,DeepFish,ssT400.ssG50,Groups,0.328337,0.056239,"[0.3213758643183255, 0.4004316375321396, 0.263..."
4,yolo8,DeepFish,ssT400.ssG50,Groups,0.328337,0.056239,"[0.3213758643183255, 0.4004316375321396, 0.263..."
5,yolo8,DeepFish,ssT400.ssG50,Groups,0.328337,0.056239,"[0.3213758643183255, 0.4004316375321396, 0.263..."
6,yolo8,DeepFish,ssT400.ssG25,Groups,0.247436,0.079007,"[0.24150644827476633, 0.34702743396645913, 0.1..."
7,yolo8,DeepFish,ssT400.ssG25,Groups,0.261061,0.123806,"[0.30186434381770244, 0.38811500873929017, 0.0..."
8,yolo8,DeepFish,ssT400.ssG25,Groups,0.283219,0.017598,"[0.302341631285015, 0.25986290568369863, 0.287..."
9,yolo8,DeepFish,ssT1000,Groups,0.419275,0.053394,"[0.3568951349812978, 0.48731601761424476, 0.41..."
10,yolo8,DeepFish,ssT1000,Groups,0.432314,0.035122,"[0.3851791243752306, 0.4423146652478878, 0.469..."
11,yolo8,DeepFish,ssT1000,Groups,0.434832,0.067729,"[0.42909142062138295, 0.5205028718707214, 0.35..."
12,yolo8,DeepFish,ssT1000.ssG50,Groups,0.385648,0.031140,"[0.34273158775676454, 0.3985501640771995, 0.41..."
13,yolo8,DeepFish,ssT1000.ssG50,Groups,0.390193,0.053060,"[0.3495259301565935, 0.46513983089723127, 0.35..."
14,yolo8,DeepFish,ssT1000.ssG50,Groups,0.391957,0.029518,"[0.42788282453628346, 0.39240485506070627, 0.3..."
15,dt2,DeepFish,ssT400,Groups,0.470629,0.011441,"[0.4620369122603882, 0.48679948536421797, 0.46..."
16,dt2,DeepFish,ssT400,Groups,0.450371,0.061089,"[0.5015116885398692, 0.48510189532309583, 0.36..."
17,dt2,DeepFish,ssT400,Groups,0.452318,0.035312,"[0.41932740037680877, 0.4363461074147031, 0.50..."
18,dt2,DeepFish,ssT400.ssG50,Groups,0.410538,0.053566,"[0.4252470082959189, 0.467539135274044, 0.3388..."
19,dt2,DeepFish,ssT400.ssG50,Groups,0.436872,0.069414,"[0.4259101119996987, 0.5268353410899099, 0.357..."
20,dt2,DeepFish,ssT400.ssG50,Groups,0.395116,0.054488,"[0.3790486157379081, 0.4684163490321119, 0.337..."
21,dt2,DeepFish,ssT400.ssG25,Groups,0.381080,0.047348,"[0.3643615786761772, 0.44559131450672196, 0.33..."
22,dt2,DeepFish,ssT400.ssG25,Groups,0.362521,0.092158,"[0.34461550319853673, 0.4832735998460644, 0.25..."
23,dt2,DeepFish,ssT400.ssG25,Groups,0.343395,0.050519,"[0.37806685225389475, 0.2719602438326942, 0.38..."
24,dt2,DeepFish,ssT1000,Groups,0.479772,0.032065,"[0.48440510993929653, 0.5165212608148015, 0.43..."
25,dt2,DeepFish,ssT1000,Groups,0.499451,0.043473,"[0.5184089826111954, 0.5406218548005338, 0.439..."
26,dt2,DeepFish,ssT1000,Groups,0.474276,0.055373,"[0.4680044145781679, 0.5450118552811115, 0.409..."
27,dt2,DeepFish,ssT1000.ssG50,Groups,0.377521,0.084310,"[0.3295056346719736, 0.49604405937331847, 0.30..."
28,dt2,DeepFish,ssT1000.ssG50,Groups,0.430836,0.080544,"[0.34228741873297885, 0.5371619485709377, 0.41..."
29,dt2,DeepFish,ssT1000.ssG50,Groups,0.469122,0.002777,"[0.4730032369435824, 0.467696965556678, 0.4666..."

# Comparing different configurations of MSRCR

In [11]:
eval_type = 'Groups' # domain-based evaluation
dataset = 'DeepFish'
results_df = []
for model in [
    'yolo8',
]:
    for augm, res_dir in [
        ('resized_MSRCR_5_27_83_new', 'SIGMAS_NEW'),
        ('resized_MSRCR_8_40_125_new', 'SIGMAS_NEW'),
        ('resized_MSRCR_15_80_250_new', 'FINAL_GROUPS'),
        ('resized_MSRCR_30_160_500_new', 'SIGMAS_NEW'),

        ('resized_MSRCR_15_80_new', 'SIGMAS_NEW'),
        ('resized_MSRCR_80_250_new', 'SIGMAS_NEW'),
        ('resized_MSRCR_15_250_new', 'SIGMAS_NEW'),
        
        ('resized_SSR_15_new', 'SIGMAS_NEW'),
        ('resized_SSR_80_new', 'SIGMAS_NEW'),
        ('resized_SSR_250_new', 'SIGMAS_NEW'),
    ]:
        train_data = f'{dataset}.CV.{eval_type}{f".{augm}" if augm else ""}'
        fn = os.path.join(results_dir, 'pickles', f'{res_dir}.{model}.{dataset}.{eval_type}.{augm}.pckl')
        if not os.path.exists(fn):
            results = utils.read_and_eval_results(
                train_datas=train_data,
                models=[model],
                model_selects=['best'],
                seeds=C.ALL_SEEDS[dataset],
                splits=['test'],
                results_dir=os.path.join(results_dir, res_dir),
                n_folds=N_FOLDS,
                concat=CCF,
                verbose=False,
            )
            utils.clean_cached_results(results)
            utils.pickle_dump(results, fn)
        else:
            results = utils.pickle_load(fn)

        r = results[train_data][model]['best']['test']
        aps = [r[s].precision.mean() for s in r]
        print(f'{model} {train_data} {np.mean(aps):.3f} {np.std(aps):.3f} {[round(ap, 3) for ap in aps]}')
        results_df.append((model, dataset, augm, eval_type, np.mean(aps), np.std(aps), aps))
assert res_dir == 'SIGMAS_NEW'
results_df = pd.DataFrame.from_records(results_df, columns=['model', 'dataset', 'pps', 'eval', 'mAP', 'std', 'mAPs'])
results_df.to_csv(os.path.join(results_dir, f'{res_dir}.csv'), index=None)
results_df

yolo8 DeepFish.CV.Groups.resized_MSRCR_5_27_83_new 0.547 0.014 [0.556, 0.526, 0.558]
yolo8 DeepFish.CV.Groups.resized_MSRCR_8_40_125_new 0.527 0.016 [0.545, 0.529, 0.506]
yolo8 DeepFish.CV.Groups.resized_MSRCR_15_80_250_new 0.551 0.012 [0.566, 0.55, 0.535]
yolo8 DeepFish.CV.Groups.resized_MSRCR_30_160_500_new 0.549 0.007 [0.549, 0.54, 0.557]
yolo8 DeepFish.CV.Groups.resized_MSRCR_15_80_new 0.509 0.049 [0.451, 0.571, 0.504]
yolo8 DeepFish.CV.Groups.resized_MSRCR_80_250_new 0.506 0.035 [0.515, 0.46, 0.544]
yolo8 DeepFish.CV.Groups.resized_MSRCR_15_250_new 0.522 0.053 [0.47, 0.595, 0.5]
yolo8 DeepFish.CV.Groups.resized_SSR_15_new 0.519 0.027 [0.534, 0.542, 0.481]
yolo8 DeepFish.CV.Groups.resized_SSR_80_new 0.496 0.032 [0.453, 0.505, 0.53]
yolo8 DeepFish.CV.Groups.resized_SSR_250_new 0.501 0.044 [0.44, 0.537, 0.526]

,model,dataset,pps,eval,mAP,std,mAPs
0,yolo8,DeepFish,resized_MSRCR_5_27_83_new,Groups,0.546528,0.014341,"[0.5557503219124639, 0.5262731188938597, 0.557..."
1,yolo8,DeepFish,resized_MSRCR_8_40_125_new,Groups,0.526584,0.016120,"[0.5451763619049933, 0.5287111399127902, 0.505..."
2,yolo8,DeepFish,resized_MSRCR_15_80_250_new,Groups,0.550555,0.012407,"[0.565872777608837, 0.5503089366107838, 0.5354..."
3,yolo8,DeepFish,resized_MSRCR_30_160_500_new,Groups,0.548746,0.006926,"[0.5487436074688262, 0.5402641827776732, 0.557..."
4,yolo8,DeepFish,resized_MSRCR_15_80_new,Groups,0.508721,0.049134,"[0.4512142405555127, 0.5712528214416791, 0.503..."
5,yolo8,DeepFish,resized_MSRCR_80_250_new,Groups,0.506134,0.034523,"[0.5145202927897201, 0.4602870678144416, 0.543..."
6,yolo8,DeepFish,resized_MSRCR_15_250_new,Groups,0.521640,0.053237,"[0.46987427512774277, 0.5948677521571623, 0.50..."
7,yolo8,DeepFish,resized_SSR_15_new,Groups,0.519078,0.027006,"[0.5340685113681319, 0.5420032033622013, 0.481..."
8,yolo8,DeepFish,resized_SSR_80_new,Groups,0.496178,0.031982,"[0.4533599625602039, 0.5049684625226986, 0.530..."
9,yolo8,DeepFish,resized_SSR_250_new,Groups,0.500885,0.043582,"[0.43953469209438134, 0.5366868853670431, 0.52..."